### ISSUE TITLE
error running mix task

### ISSUE THREAD

**Issue by sescobb27** [hauleth/mix_unused#16]
iex version: 
```
$ iex
Erlang/OTP 24 [erts-12.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]
Interactive Elixir (1.12.3) - press Ctrl+C to exit (type h() ENTER for help)
```

once i ran the command it failed

```
$ mix compile.unused
** (MatchError) no match of right hand side value: {:error, {:already_started, #PID<0.281.0>}}
    lib/mix/tasks/compile.unused.ex:90: Mix.Tasks.Compile.Unused.run/1
    (mix 1.12.3) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.3) lib/mix/project.ex:353: Mix.Project.in_project/4
    (elixir 1.12.3) lib/file.ex:1560: File.cd!/2
    (mix 1.12.3) lib/mix/task.ex:520: anonymous fn/4 in Mix.Task.recur/1
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.12.3) lib/mix/task.ex:519: Mix.Task.recur/1
    (mix 1.12.3) lib/mix/project_stack.ex:181: Mix.ProjectStack.recur/1
```

using
```elixir
{:mix_unused, "~> 0.2.0"}
```

**Comment by sescobb27** [comment]
🙈 sorry for the miss usage, i saw it was a mix task and run it alone. thanks for checking up tho

**Comment by hauleth** [comment]
It should be resolved now.
