### ISSUE TITLE
Compilation error: protocol Enumerable not implemented for nil of type Atom

### ISSUE THREAD

**Issue by RKushnir** [hauleth/mix_unused#35]
Hi,

When trying to use the package, unfortunately, the compilation fails with the following error. It seems that `Application.spec/2` somehow is returning nil. This is in a context of an umbrella app, if that matters.

```
could not compile dependency :my_app, "mix compile" failed.
You can recompile this dependency with "mix deps.compile my_app", update it with "mix deps.update my_app" or clean it with "mix deps.clean my_app"

** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom
(elixir 1.12.3) lib/enum.ex:1: Enumerable.impl_for!/1
(elixir 1.12.3) lib/enum.ex:141: Enumerable.reduce/3
(elixir 1.12.3) lib/enum.ex:3958: Enum.flat_map/2
(mix_unused 0.4.0) lib/mix_unused/exports.ex:22: MixUnused.Exports.application/1
(mix_unused 0.4.0) lib/mix/tasks/compile.unused.ex:136: Mix.Tasks.Compile.Unused.after_compiler/5
(elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
(mix 1.12.3) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
(mix 1.12.3) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
```

**Comment by RKushnir** [comment]
Could we check the return value of [Application.load](https://github.com/hauleth/mix_unused/blob/8f328518f6a8fd7c560f5eeaaefbb7c53d5f5c2a/lib/mix_unused/exports.ex#L18) to see the error if the application fails to load?
